# Generated by Django 4.2.4 on 2024-05-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
